pipeline {
    agent any

    environment {
        IMAGE_NAME = 'lovenesh03/jenkins-flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        
    }

    
    stages {

        stage('Setup') {
            steps {
                sh '''
                    # Wait for apt lock (due to unattended upgrades)
                    while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
                        echo "Waiting for apt lock..."
                        sleep 5
                    done

                    sudo apt update
                    sudo apt install -y python3-pip python3-venv

                    # Create and activate virtual environment
                    python3 -m venv venv
                    source venv/bin/activate

                    pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
            }
        }

        stage('Login to docker hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'}
                echo 'Login successfully'
            }
        }

        stage('Build Docker Image')
        {
            steps
            {
                sh 'docker build -t ${IMAGE_TAG} .'
                echo "Docker image build successfully"
                sh 'docker image ls'
                
            }
        }

        stage('Push Docker Image')
        {
            steps
            {
                sh 'docker push ${IMAGE_TAG}'
                echo "Docker image push successfully"
            }
        }      
    }
}